### ISSUE TITLE
Allow to specify the folder for backups and restores

### ISSUE THREAD

**Issue by clochix** [cozy/python_cozy_management#10]
It would be nice is user could select the folder where backups are saved and the full path of the file (s)he would like to restore.

**Comment by clochix** [comment]
Another user is requesting this feature.

**Comment by nicofrand** [comment]
Looks to me that you can already specify the full path of the file you want to restore : https://github.com/cozy/python_cozy_management/blob/master/cozy_management/backup.py#L51.

The remaining need is to be able to specify the full path of the backup file you want to export.

**Comment by Phyks** [comment]
I am definitely interested in this. Would you like a PR to offer the ability to specify backup output file?

**Comment by clochix** [comment]
All PR are welcome, thanks @Phyks ☺
