### ISSUE TITLE
Lets Encrypt integration

### ISSUE THREAD

**Issue by ghost** [cozy/python_cozy_management#12]
As cozy_management provides certificates for the installed cozy, could it generate valid certificates through letsencrypt ? Especially now that beta stage is over :)

**Comment by clochix** [comment]
Hi @oudimou,

Thanks for suggesting. We definitively should have a look to see if we could integrate Let's encrypt management into cozy_management.

**Comment by ghost** [comment]
@clochix Cool !
Looking forward to see it implemented, especially now that I received my PINE64 board ;)

**Comment by nledez** [comment]
Closed in https://github.com/cozy/python_cozy_management/commit/401998714a5fe031edfb4062b162d11b0a760db6
