### ISSUE TITLE
Docs: Mention that this package is intended for use with Debian systems

### ISSUE THREAD

**Issue by gruentee** [cozy/python_cozy_management#13]
Although one can probably derive from package names mentioned in the dependecies section that this package is intended for use on Debian (-alike) systems, I think that should be mentioned explicitly elsewhere.

Otherwise people trying to run it on other systems (here CentOS) get something like

``` sh
cozy_management install_requirements/bin/sh: debconf-set-selections: Command not found.
/bin/sh: apt-get: Command not found.
/bin/sh: apt-get: Command not found.
/bin/sh: apt-get: Command not found.
```

**Comment by clochix** [comment]
Thanks for reporting @gruentee, we'll add a warning at the top of README.

See #15 

Some commands are specifics to Debian, but other should work on most distros.
