### ISSUE TITLE
Document the install_cozy procedure

### ISSUE THREAD

**Issue by babolivier** [cozy/python_cozy_management#18]
I know it's not an absolute priority. I think it'd be great to have an up to date and explicit documentation on what the install_cozy actually does, as it's like one big magic block, quite opaque if you don't have the time to dive into the codebase. This makes it really annoying for the support, as I just found myself having to answer ASAP to an user about a certificate issue, and didn't even know how it does it (as it changed over time), whereas before I just had to check the corresponding bash script.

It'll also make it really hard for me to maintain the Archlinux package since this command doesn't work on this distro, and, well, maintaining a package can be hard if you're not aware of the changes in the install procedure.

**Comment by clochix** [comment]
I agree this should be better documented.

In fact, the `install_cozy` is quite simple:
- it install some requirements: the `cozy-apt-node-list` package, which allow to install Node.js 4 on Jessie. Then it install Node.js, and the `coy-depends` package;
- then install the `cozy` package.

What's really hard is that now, the dependencies and the installation script are split into several packages, and you have to dig into each of them.

**Comment by clochix** [comment]
Thanks @nledez ♥

@babolivier feel free to suggest improvements to this documentation if some points are not clear.

**Comment by babolivier** [comment]
Thanks @nledez!

I'll give it a deeper look later, but right now it seems to be ok :smile:
