### ISSUE TITLE
Update acme-tiny

### ISSUE THREAD

**Issue by Toobian** [cozy/python_cozy_management#19]
Let's Encrypt signature not working because Term's of Service changes.

acme-tiny has been updated to fix this. (https://github.com/diafygi/acme-tiny/commit/ecd26b1e784973e5b52d5a308964a8e29a6cf207)

**Comment by nledez** [comment]
I try to fix this ASAP.

**Comment by jsilvestre** [comment]
We've taken into account this request and will proceed to push a fix. I let you know when it's done!

**Comment by aeris** [comment]
Fixed and tested on 2c59269f4a15f269100e4858c0a279c6f2cb847f !
