### ISSUE TITLE
libjpeg-dev missing for weboob installation

### ISSUE THREAD

**Issue by Toobian** [cozy/python_cozy_management#20]
When I try to install weboob with cozy_management, somes errors with Pillow dependencies happened.

To solve that we need to install libjpeg-dev (Ubuntu 14.04.5 LTS).

Maybe cozy_management can install this dependency ?

**Comment by clochix** [comment]
Ping @nledez

**Comment by nledez** [comment]
The problem is on cozy package not this one.
By the way, it's fixed with another way soon.

**Comment by clochix** [comment]
Thanks for reporting @Toobian ☺

**Comment by wangkesen** [comment]
Got the same error today actually :(
