### ISSUE TITLE
Backup and restore should use get_database_dir

### ISSUE THREAD

**Issue by clochix** [cozy/python_cozy_management#6]
For now, backup and restore commands assume the database is at the default location. This command should call `get_database_dir()` to get the real database path.

Refs:
- https://github.com/cozy/python_cozy_management/blob/master/cozy_management/backup.py#L25
- https://github.com/cozy/python_cozy_management/blob/master/cozy_management/backup.py#L42
- https://github.com/cozy/python_cozy_management/blob/master/cozy_management/couchdb.py#L248

**Comment by nledez** [comment]
Thanks @CPatchane
